Testing try-catch-finally
==CODE==
import std.io.*;
try {
	throw "yay!";

	println(1);
} catch (e) {
	printf("Caught: \1\n", e);
} finally {
	println(3);
}
==RESULT==
Caught: yay!
3
